name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    name: Run Python Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        pip install -r src/requirements.txt
        
    - name: Run basic syntax check
      run: |
        python -m py_compile src/nutrition_processor.py
        echo "✅ Python syntax is valid"

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t nutrition-analysis:latest .
        
    - name: Test Docker image
      run: |
        docker run --rm nutrition-analysis:latest echo "✅ Docker container works!"

  deploy:
    name: Deploy Simulation
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build and run application
      run: |
        docker build -t nutrition-analysis:latest .
        docker run --rm nutrition-analysis:latest